### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by DatrixTHLK** [AdrienJaguenet/Kardashev#1]
Civilization is spelled incorrectly. While I know this may be insignificant, it means that not enough care was put into the game or that your first language isn't english. In either case though it would make the game much more professional if you could fix that.

**Comment by AdrienJaguenet** [comment]
Hi,
in case you're referring to that, both “civilisation” and “civilization” are correct spellings of the same word. The former is mostly common in Britain.

Sources:
* https://www.merriam-webster.com/dictionary/civilisation
* https://www.collinsdictionary.com/dictionary/english/civilisation
* https://dictionary.cambridge.org/dictionary/english/civilization?q=civilisation

More info on the topic of British and American spellings of English: https://en.wikipedia.org/wiki/American_and_British_English_spelling_differences
